// FPSTrainingGameMode.cpp
#include "FPSTrainingGameMode.h"
#include "TrainingRoom.h"
#include "GameFramework/PlayerStart.h"
#include "Engine/DirectionalLight.h"
#include "Engine/PointLight.h"
#include "Components/DirectionalLightComponent.h"
#include "Components/PointLightComponent.h"
#include "UObject/ConstructorHelpers.h"
#include "Kismet/GameplayStatics.h"

AFPSTrainingGameMode::AFPSTrainingGameMode()
{
	// Set default pawn class to FirstPerson character
	static ConstructorHelpers::FClassFinder<APawn> PlayerPawnBPClass(
		TEXT("/Game/FirstPerson/Blueprints/BP_FirstPersonCharacter")
	);
	if (PlayerPawnBPClass.Class != nullptr)
	{
		DefaultPawnClass = PlayerPawnBPClass.Class;
	}
	
	// Set player controller class
	static ConstructorHelpers::FClassFinder<APlayerController> PlayerControllerBPClass(
		TEXT("/Game/FirstPerson/Blueprints/BP_FirstPersonPlayerController")
	);
	if (PlayerControllerBPClass.Class != nullptr)
	{
		PlayerControllerClass = PlayerControllerBPClass.Class;
	}
}

void AFPSTrainingGameMode::BeginPlay()
{
	Super::BeginPlay();
	
	// ===== ALL SCENE GENERATION MOVED TO PYTHON =====
	// Map: Cosmos_002_Training_World
	// Generated by: Scripts/MapGenerators/generate_cosmos_002_training_world.py
	//
	// The Python script creates:
	// - TrainingRoom Actor (3 rooms with transparent partitions)
	// - PlayerStart
	// - Directional Light (sun)
	// - Sky Light (ambient)
	// - Point Lights (3 room lights)
	//
	// No dynamic spawning needed - everything is pre-placed in the map
	
	UE_LOG(LogTemp, Display, TEXT("FPSTrainingGameMode initialized (using Python-generated static map)"));
}
